apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ssp-local

resources:
  - ssp--ids--local--psql--persistent-volume.yaml
  - ssp--ids--local--psql--persistent-volume-claim.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ids-config
    namespace: ssp-local
    literals:
      - Certificate__Password=password
      - Certificate__Path=keystore/certificate.pfx
      - Certificate__UseHttps=false
      - ConnectionStrings__DefaultConnection="Host=ids-psql-service;Port=4053;Database=app_db;Username=admin;Password=admin_pass"
      - IdentityServer__FrontendCorsOrigin=https://smartscrumpoker.localhost.balazskrizsan.com
      - IdentityServer__FrontendRedirectUri=https://smartscrumpoker.localhost.balazskrizsan.com/auth-callback
      - IdentityServer__IssuerUri=https://ids--smartscrumpoker.localhost.balazskrizsan.com
      - IdentityServer__Port=8080
