apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssp--ids--local--dp-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
