apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssp--backend--uat--psql--persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: ssp--backend--uat--psql--persistent-volume
  resources:
    requests:
      storage: 10Gi
