apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssp--backend--local--psql--persistent-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssp/ssp__backend__local__psql__persistent_volume"
