apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ssp-uat

resources:
  - ../templates

configMapGenerator:
  - name: fluent-bit-env
    namespace: ssp-uat
    literals:
      - env=UAT
      - logstash_host=logstash.elk.svc.cluster.local
      - logstash_port=5044

generatorOptions:
  disableNameSuffixHash: true
