apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - ../../apps/common/local
#  - ../../apps/elastalert/local
  - ../../apps/elastic/ubuntu
#  - ../../apps/kibana/local
#  - ../../apps/logstash/local
#  - ../../apps/semantic-log-classifier/local
#  - ../../apps/elastic-fetcher/local
