apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk--elastic-fetcher--local--psql--persistent-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssp/elk__elastic_fetcher__local__psql__persistent_volume"
