apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk--elastic-fetcher--local--psql--persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: elk--elastic-fetcher--local--psql--persistent-volume
  resources:
    requests:
      storage: 10Gi
