apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ssp-local

resources:
  - elk--elastic-fetcher--local--psql--persistent-volume.yaml
  - elk--elastic-fetcher--local--psql--persistent-volume-claim.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: elastic-fetcher-config
    namespace: ssp-local
    literals:
      - SERVER_ENV=local
      - SERVER_PORT=4103
      - SPRING_DATASOURCE_URL=jdbc:postgresql://elastic-fetcher-psql:4083/app_db
      - SPRING_FLYWAY_URL=jdbc:postgresql://elastic-fetcher-psql:4083/app_db
      - NATIVE_REFLECTION_CONFIGURATION_GENERATOR_ENABLED=false
      - APP__ELASTIC_FETCHER_TASK_ENABLED=true
      - APP__ELASTIC_HOST=elasticsearch
      - APP__ELASTIC_PORT=9200
      - APP__ELASTIC_SCHEME=http
      - APP__ELASTIC_INDEX_NAME=alerting-logs-local
      - APP__ELASTIC_INDEX_ERROR_NAME=ssp-local-logs*
      - LOGBACK_LOGSTASH_ENABLED=false
      - LOGBACK_LOGSTASH_FULL_HOST=
