apiVersion: v1
kind: Service
metadata:
  name: semantic-log-classifier-psql-service
spec:
  type: ClusterIP
  ports:
    - port: 1111
      targetPort: 5432
  selector:
    app: semantic-log-classifier-psql-label
