apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-cd-fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-cd-fluent-bit
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-cd-fluent-bit
subjects:
- kind: ServiceAccount
  name: argo-cd-fluent-bit
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: argo-cd-fluent-bit
  apiGroup: rbac.authorization.k8s.io
