apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-aws-services
  labels:
    app: fluent-bit-aws-services
spec:
  selector:
    matchLabels:
      app: fluent-bit-aws-services
  template:
    metadata:
      labels:
        app: fluent-bit-aws-services
    spec:
      initContainers:
      - name: config-subst
        image: alpine:3.18
        command:
        - /bin/sh
        - -c
        - |
          export APP_NAME=$(cat /env-config/app_name)
          export ENV=$(cat /env-config/env)
          export LANGUAGE=$(cat /env-config/language)
          export LOGSTASH_HOST=$(cat /env-config/logstash_host)
          export LOGSTASH_PORT=$(cat /env-config/logstash_port)

          echo "APP_NAME: $APP_NAME"
          echo "ENV: $ENV"
          echo "LANGUAGE: $LANGUAGE"
          echo "LOGSTASH_HOST: $LOGSTASH_HOST"
          echo "LOGSTASH_PORT: $LOGSTASH_PORT"
          
          
          cp /fluent-bit-filebased-configmap-source/fluent-bit.conf /fluent-bit-filebased-configmap/fluent-bit.conf
          cp /fluent-bit-filebased-configmap-source/parsers.conf /fluent-bit-filebased-configmap/parsers.conf

          echo "/fluent-bit-filebased-configmap/fluent-bit.conf:"
          echo "====================="
          cat /fluent-bit-filebased-configmap/fluent-bit.conf
          echo "====================="
          echo "/fluent-bit-filebased-configmap/parsers.conf:"
          echo "====================="
          cat /fluent-bit-filebased-configmap/parsers.conf
          echo "====================="

          sed -e "s/@APP_NAME@/$APP_NAME/g" \
              -e "s/@ENV@/$ENV/g" \
              -e "s/@LANGUAGE@/$LANGUAGE/g" \
              -e "s/@LOGSTASH_HOST@/$LOGSTASH_HOST/g" \
              -e "s/@LOGSTASH_PORT@/$LOGSTASH_PORT/g" \
              /fluent-bit-filebased-configmap/fluent-bit.conf > /fluent-bit-filebased-configmap/fluent-bit.conf.tmp
          mv /fluent-bit-filebased-configmap/fluent-bit.conf.tmp /fluent-bit-filebased-configmap/fluent-bit.conf
        volumeMounts:
        - name: fluent-bit-filebased-configmap-source
          mountPath: /fluent-bit-filebased-configmap-source
          readOnly: true
        - name: fluent-bit-filebased-configmap
          mountPath: /fluent-bit-filebased-configmap
        - name: fluent-bit-env
          mountPath: /env-config
      containers:
      - name: fluent-bit-aws-services
        image: fluent/fluent-bit:2.2.0
        imagePullPolicy: Always
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-filebased-configmap
          mountPath: /fluent-bit/etc/
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-filebased-configmap-source
        configMap:
          name: fluent-bit-filebased-configmap
      - name: fluent-bit-filebased-configmap
        emptyDir: {}
      - name: fluent-bit-env
        configMap:
          name: fluent-bit-env-aws-services
