apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids
  labels:
    app: ids-label
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ids
  template:
    metadata:
      labels:
        app: ids-label
        service: ids
    spec:
      containers:
        - name: ids
          image: placeholder:placeholder
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
#          readinessProbe:
#            httpGet:
#              path: /.well-known/openid-configuration
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            timeoutSeconds: 5
#            failureThreshold: 3
#          livenessProbe:
#            httpGet:
#              path: /.well-known/openid-configuration
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 30
#            timeoutSeconds: 5
#            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 400Mi
          envFrom:
            - configMapRef:
                name: ids-config
#            - secretRef:
#                name: ids-secrets
