apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ssp-local

resources:
  - app-config
  - ../templates

patches:
  - target: { group: "apps", version: "v1", kind: "Deployment", name: "semantic-log-classifier" }
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: kbalazsworks/semantic_log_classifier_api:commit_sha_short_3e142de

  - target: { group: "", version: "v1", kind: "Service", name: "semantic-log-classifier" }
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer

      - op: replace
        path: /spec/ports/0/port
        value: 4073

  - target: { group: "networking.k8s.io",  version: "v1", kind: "Ingress", name: "semantic-log-classifier" }
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 4073

      - op: replace
        path: /spec/rules/0/host
        value: api--semantic-log-classifier--smartscrumpoker.localhost.balazskrizsan.com

      - op: replace
        path: /spec/tls/0/hosts
        value:
          - api--semantic-log-classifier--smartscrumpoker.localhost.balazskrizsan.com

### PSQL

  - target: { group: "", version: "v1", kind: "Service", name: "semantic-log-classifier-psql" }
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 4083

  - target: { group: "", version: "v1", kind: "Service", name: "semantic-log-classifier-psql" }
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer

  - target: { group: "apps", version: "v1", kind: "Deployment", name: "semantic-log-classifier-psql" }
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: elk--semantic-log-classifier--local--psql--persistent-volume-claim
