apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/common/ubuntu
#  - ../../apps/elastalert/local
  - ../../apps/elastic/ubuntu
#  - ../../apps/kibana/local
  - ../../apps/logstash/ubuntu
#  - ../../apps/semantic-log-classifier/local
#  - ../../apps/elastic-fetcher/local
