apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssp--local--app
  namespace: argocd
spec:
  destination:
    namespace: ssp-local
    server: https://kubernetes.default.svc
  project: default
  source:
    path: src/app-groups/ssp/scripts/local
    repoURL: https://github.com/balazskrizsan/argo_ubuntu
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
