apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev-db
  name: elastic-fetcher-api-psql-dev
  labels:
    app: elastic-fetcher-api-psql-dev-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-fetcher-api-psql-dev-label
  template:
    metadata:
      labels:
        app: elastic-fetcher-api-psql-dev-label
    spec:
      containers:
        - name: postgres
          image: postgres:16.2
          ports:
            - containerPort: 5432
          imagePullPolicy: IfNotPresent
          resources: {}
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin_pass
            - name: POSTGRES_DB
              value: app_db
            - name: PGDATA
              value: /data/postgres
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev-db
  name: elastic-fetcher-api-psql-dev
spec:
  type: LoadBalancer
  ports:
    - port: 4110
      targetPort: 5432
  selector:
    app: elastic-fetcher-api-psql-dev-label
