apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-restore-job
  namespace: elk-local
spec:
#  schedule: "* * * * *"
#  successfulJobsHistoryLimit: 2
#  failedJobsHistoryLimit: 5
#  jobTemplate:
#    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
            - name: cleanup
              image: busybox
              command: [ "sh", "-c", "rm -rf /usr/share/elasticsearch/backup/*" ]
              volumeMounts:
                - name: backup-volume
                  mountPath: /usr/share/elasticsearch/backup
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: elastic-backup-pvc
          containers:
          - name: kubectl
            image: kbalazsworks/kubernetes_job_base_image:0.3
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: cloud-secrets-elk
            volumeMounts:
              - name: backup-volume
                mountPath: /usr/share/elasticsearch/backup
            command: ["/bin/sh", "-c"]
            args:
              - |
                aws configure set aws_access_key_id "$AWS_S3_SERVICE_ACCOUNT_ACCESS_KEY_ID"
                aws configure set aws_secret_access_key "$AWS_S3_SERVICE_ACCOUNT_ACCESS_KEY"
                aws configure set region "$AWS_S3_BACKUP_REGION"
                
                LATEST_BACKUP_FILE="$AWS_S3_BACKUP_SSP_ELASTIC_PATH/latest.txt"
                LATEST_BACKUP_REPO_FILE="$AWS_S3_BACKUP_SSP_ELASTIC_PATH/latest_repo.txt"
                
                mkdir /restore
                
                aws s3 cp "s3://$AWS_S3_BACKUP_BUCKET$LATEST_BACKUP_FILE" "/restore/latest.txt"
                cat "/restore/latest.txt"
                
                aws s3 cp "s3://$AWS_S3_BACKUP_BUCKET$LATEST_BACKUP_REPO_FILE" "/restore/latest_repo.txt"
                cat "/restore/latest_repo.txt"
                
                echo "s3://$AWS_S3_BACKUP_BUCKET/$(cat /restore/latest.txt)"
                aws s3 cp "s3://$AWS_S3_BACKUP_BUCKET$AWS_S3_BACKUP_SSP_ELASTIC_PATH/$(cat /restore/latest.txt)" "/restore/backup.zip"
                
                ls -hal "/restore"
                
                unzip "/restore/backup.zip" -d "/"
                
                # ls -halR "/usr/share/elasticsearch/backup"
                
                curl -X PUT "http://elasticsearch:9200/_snapshot/$(cat /restore/latest_repo.txt)" -H 'Content-Type: application/json' -d'
                {
                  "type": "fs",
                  "settings": {
                    "location": "/usr/share/elasticsearch/backup",
                    "compress": true
                  }
                }'
                
                curl -X POST "http://elasticsearch:9200/_snapshot/$(cat /restore/latest_repo.txt)/snapshot_2025-03-28_22:12:57/_restore?wait_for_completion=true" -H 'Content-Type: application/json' -d'
                {
                  "indices": "*",
                  "ignore_unavailable": true,
                  "include_global_state": true,
                  "rename_pattern": "(.+)",
                  "rename_replacement": "$1"
                }'
                
                curl -X DELETE "http://elasticsearch:9200/_snapshot/$(cat /restore/latest_repo.txt)/snapshot_2025-03-28_22:12:57"

                curl -X DELETE "http://elasticsearch:9200/_snapshot/$(cat /restore/latest_repo.txt)"
