apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-filebased-configmap
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*@APP_NAME@*.log
        Parser            docker
        Tag               @APP_NAME@.*
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  5
        Read_from_Head    On

    [FILTER]
        Name                kubernetes
        Match               @APP_NAME@.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     @APP_NAME@.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [FILTER]
        Name                modify
        Match               @APP_NAME@.*
        Add                 env @ENV@
        Add                 app_name @APP_NAME@

    [OUTPUT]
        Name            tcp
        Match           @APP_NAME@.*
        Host            @LOGSTASH_HOST@
        Port            @LOGSTASH_PORT@
        Format          json_lines
        json_date_key   @timestamp
        json_date_format iso8601

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
