apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ssp-local

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: backend-config
    namespace: ssp-local
    literals:
      - AWS_ACCESS_KEY_ID=
      - AWS_REGION=
      - AWS_SECRET_ACCESS_KEY=
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY_STORE=classpath:keystore/certificate.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
