apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ssp-local

resources:
  - app-config
  - ../templates

patches:
  - target: { group: "apps", version: "v1", kind: "Deployment", name: "elastic-fetcher" }
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: kbalazsworks/elastic_fetcher_api:commit_sha_short_22545b2

  - target: { group: "", version: "v1", kind: "Service", name: "elastic-fetcher" }
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer

      - op: replace
        path: /spec/ports/0/port
        value: 4103

  - target: { group: "networking.k8s.io",  version: "v1", kind: "Ingress", name: "elastic-fetcher" }
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 4103

      - op: replace
        path: /spec/rules/0/host
        value: api--elastic-fetcher--smartscrumpoker.localhost.balazskrizsan.com

      - op: replace
        path: /spec/tls/0/hosts
        value:
          - api--elastic-fetcher--smartscrumpoker.localhost.balazskrizsan.com

### PSQL

  - target: { group: "", version: "v1", kind: "Service", name: "elastic-fetcher-psql" }
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 4083

  - target: { group: "", version: "v1", kind: "Service", name: "elastic-fetcher-psql" }
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer

  - target: { group: "apps", version: "v1", kind: "Deployment", name: "elastic-fetcher-psql" }
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: elk--elastic-fetcher--local--psql--persistent-volume-claim
