apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-config.yaml
  - ../../apps/argo-cd/local
  - ../../apps/fluent-bit/local
  - ../../apps/minikube-dashboard/local
