apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-config.yaml
  - ../../apps/common/templates/cert-manager
  - ../../apps/aws-services/local
#  - ../../apps/ids/local
  - ../../apps/backend/local
  - ../../apps/frontend/local
