apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ../templates

configMapGenerator:
  - name: argo-cd-fluent-bit-env
    namespace: argocd
    literals:
      - env=local
      - app=argo-cd
      - logstash_host=logstash.elk-local.svc.cluster.local
      - logstash_port=5044

generatorOptions:
  disableNameSuffixHash: true
