apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-config.yaml
  - ../../apps/common/ubuntu
  - ../../apps/fluent-bit/ubuntu_uat
  - ../../apps/aws-services/ubuntu_uat
  - ../../apps/identity-service/ubuntu_uat
  - ../../apps/backend/ubuntu_uat
  - ../../apps/frontend/ubuntu_uat
