apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssp--ids--uat--dp-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: ssp--ids--uat--dp-persistent-volume
  resources:
    requests:
      storage: 1Gi
