apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ssp-local

resources:
  - app-config
  - ../templates
  - ../templates/fluent-bit
  - ../../common/insecure-config

patches:
  - target: { group: "apps", version: "v1", kind: "Deployment", name: "aws-services" }
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: kbalazsworks/smart_scrum_poker_v2_aws_services:commit_sha_short_d147737

  - target: { group: "", version: "v1", kind: "Service", name: "aws-services" }
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer

      - op: replace
        path: /spec/ports/0/port
        value: 1234

  - target: { group: "networking.k8s.io",  version: "v1", kind: "Ingress", name: "aws-services" }
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/port/number
        value: 1234

      - op: replace
        path: /spec/rules/0/host
        value: api--aws-services--smartscrumpoker.localhost.balazskrizsan.com

      - op: replace
        path: /spec/tls/0/hosts
        value:
          - api--aws-services--smartscrumpoker.localhost.balazskrizsan.com

### Fluent Bit

  - target: { group: "", version: "v1", kind: "ConfigMap", name: "fluent-bit-env" }
    patch: |-
      - op: replace
        path: /data/app_name
        value: aws-services

      - op: replace
        path: /data/language
        value: java
