apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk--semantic-log-classifier--local--psql--persistent-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssp/elk__semantic_log_classifier__local__psql__persistent_volume"
