apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk--semantic-log-classifier--local--psql--persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
