apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-config.yaml
#  - ../../apps/common/ubuntu
#  - ../../apps/fluent-bit/ubuntu
#  - ../../apps/aws-services/ubuntu
#  - ../../apps/identity-service/ubuntu
#  - ../../apps/backend/ubuntu
#  - ../../apps/frontend/ubuntu
