apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssp--ids--prod--dp-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
