apiVersion: v1
kind: Secret
metadata:
  name: elastalert-pushover-secrets
  namespace: elk-local
type: Opaque
stringData:
  PUSHOVER_TOKEN: "a4tf8w3hau5nqzz5zcpoc5nsru1zqy"
  PUSHOVER_USER: "u8UgHuakHU3vw4YboUxaTqQ9ouPTJB"
